title: Elizabeth K. Weaver # your name here
logo: "/images/EW_portfolio_profile_picture.png" # your photo here
description: > # your text below (remove <br> elements if line breaks not needed)
  Hello!
  <br><br>
  I’m a <strong>Data Analyst</strong> specialized in helping companies answer important business questions with data. My experience comes from the Digital Marketing space, where I’ve consulted enterprise-level brands on how to maximize the return on their digital marketing dollars. My agency experience has shaped me to be a trusted client and internal partner, an always-curious researcher, and a proud data nerd.
  <br><br>
  Here, I'm sharing details on some of my favorite projects that I've worked on, professionally and personally. 
  <br><br>
  Thanks for visiting! Let's connect!
  <br>
  -EW
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
